services:
  mongo:
    container_name: ${DOCKER_PREFIX_NAME}-${DOCKER_PREFIX_ENV}-mongodb
    image: bitnami/mongodb:7.0.5
    environment:
      - MONGODB_USERNAME=${DOCKER_MONGODB_USERNAME}
      - MONGODB_PASSWORD=${DOCKER_MONGODB_PASSWORD}
      - MONGODB_DATABASE=${DOCKER_MONGODB_DATABASE}
      - MONGODB_ROOT_USER=${DOCKER_MONGODB_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${DOCKER_MONGODB_ROOT_PASSWORD}
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${DOCKER_MONGODB_REPLICA_SET_KEY}
      - EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU=1
    ports:
      - ${DOCKER_MONGODB_EXPOSE}:27017
    volumes:
      - data:/bitnami/mongodb
    networks:
      - npm
    restart: on-failure
volumes:
  data:
    name: ${DOCKER_PREFIX_NAME}-${DOCKER_PREFIX_ENV}-mongodb

networks:
  npm:
    external: true
